#!/usr/bin/env python3
"""Build the inspected-primary-source matrix and reproducible search log."""

from __future__ import annotations

from qroute_dilution.io import PROJECT_ROOT, atomic_write_csv

import pandas as pd


RESULT_ROOT = PROJECT_ROOT / "results/theory_validation_v2"
TIMESTAMP = "2026-08-29T04:10:18Z"


SEARCHES = [
    ("S001", "quantum search lower bound multiple marked items", "arxiv.org", 8, 3, 2),
    ("S002", "Grover search M marked items lower bound", "arxiv.org", 8, 3, 2),
    ("S003", "average success probability q-query quantum search", "arxiv.org", 9, 4, 2),
    ("S004", "hybrid argument quantum search marked subset BBBV", "epubs.siam.org;arxiv.org", 7, 2, 1),
    ("S005", "Zalka optimality Grover multiple solutions", "link.aps.org;arxiv.org", 8, 2, 1),
    ("S006", "arbitrary phase quantum search lower bound", "arxiv.org", 9, 3, 2),
    ("S007", "phase-matched amplitude amplification", "arxiv.org;link.aps.org", 7, 2, 1),
    ("S008", "amplitude amplification multiple marked states", "arxiv.org", 8, 2, 2),
    ("S009", "quantum query complexity random marked set", "arxiv.org", 8, 3, 1),
    ("S010", "average-case unstructured quantum search", "arxiv.org", 8, 3, 1),
    ("S011", "adaptive quantum query search lower bound", "arxiv.org", 8, 3, 1),
    ("S012", "variable-time quantum search lower bound", "arxiv.org", 7, 3, 2),
    ("S013", "intermediate measurement quantum query lower bound", "arxiv.org", 7, 2, 1),
    ("S014", "variational quantum algorithm query complexity", "arxiv.org;epubs.siam.org", 8, 3, 1),
    ("S015", "QAOA query complexity lower bound oracle Grover", "arxiv.org", 8, 3, 1),
    ("S016", "trained QAOA total query complexity", "arxiv.org", 8, 2, 1),
    ("S017", "constrained QAOA feasible fraction dilution", "arxiv.org", 8, 3, 2),
    ("S018", "feasibility probability QAOA", "arxiv.org", 8, 3, 2),
    ("S019", "resource constrained shortest path explicit additive resources", "onlinelibrary.wiley.com;sciencedirect.com", 8, 3, 2),
    ("S020", "exact quantum lower bound Grover Dohotaru Hoyer", "arxiv.org;qic.rintonpress.com", 6, 2, 1),
    ("S021", "arbitrary phase oracle hybrid lower bound Gilyen", "arxiv.org;epubs.siam.org", 7, 2, 1),
]


SOURCES = [
    {
        "citation_id": "BBBV1997",
        "authors": "Charles H. Bennett; Ethan Bernstein; Gilles Brassard; Umesh Vazirani",
        "title": "Strengths and Weaknesses of Quantum Computing",
        "year": 1997,
        "venue": "SIAM Journal on Computing 26(5):1510-1523",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1137/S0097539796300933",
        "arxiv_id": "quant-ph/9701001",
        "primary_url": "https://arxiv.org/abs/quant-ph/9701001",
        "theorem_or_result_location": "oracle-search hybrid argument; journal abstract and author/arXiv manuscript inspected",
        "model": "quantum oracle computation",
        "number_of_marked_items": "unique marked item in search consequence",
        "average_worst_or_pointwise": "random-oracle/almost-sure and worst-case consequences",
        "adaptive_or_nonadaptive": "general oracle algorithm; measurements may be deferred",
        "fixed_or_arbitrary_phase": "standard Boolean oracle",
        "ancillas": "general work space",
        "exact_constant": "no match to v1 coefficient identified",
        "asymptotic_bound": "Omega(sqrt(N))",
        "relation_to_v1_theorem": "foundational hybrid lower bound",
        "relation_to_adaptive_extension": "supports standard unitary-query normalization",
        "novelty_implication": "coarse search scaling is classical prior art",
    },
    {
        "citation_id": "BBHT1998",
        "authors": "Michel Boyer; Gilles Brassard; Peter Hoyer; Alain Tapp",
        "title": "Tight Bounds on Quantum Searching",
        "year": 1998,
        "venue": "Fortschritte der Physik 46(4-5):493-505",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1002/(SICI)1521-3978(199806)46:4/5<493::AID-PROP493>3.0.CO;2-P",
        "arxiv_id": "quant-ph/9605034",
        "primary_url": "https://arxiv.org/html/quant-ph/9605034",
        "theorem_or_result_location": "Section 3 equations (3), (8)-(9); Section 7 improved lower bound",
        "model": "unstructured table/oracle search",
        "number_of_marked_items": "t marked items, known and unknown t",
        "average_worst_or_pointwise": "algorithmic success and general lower bound",
        "adaptive_or_nonadaptive": "includes randomized restarts for unknown t",
        "fixed_or_arbitrary_phase": "standard Grover marking",
        "ancillas": "general lower-bound algorithm",
        "exact_constant": "near-optimal query constant; exact Grover formula",
        "asymptotic_bound": "Theta(sqrt(N/t))",
        "relation_to_v1_theorem": "P-A and achievability preexist; not v1 phase sum",
        "relation_to_adaptive_extension": "variable/restart search algorithm, not v2 hard-cap proof",
        "novelty_implication": "multiple-marked scaling is known",
    },
    {
        "citation_id": "Zalka1999",
        "authors": "Christof Zalka",
        "title": "Grover's quantum searching algorithm is optimal",
        "year": 1999,
        "venue": "Physical Review A 60:2746-2751",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1103/PhysRevA.60.2746",
        "arxiv_id": "quant-ph/9711070",
        "primary_url": "https://arxiv.org/html/quant-ph/9711070",
        "theorem_or_result_location": "equations (6)-(8), discussion lines 86-100, Appendix 5.1",
        "model": "unique-marked unstructured oracle search",
        "number_of_marked_items": "one",
        "average_worst_or_pointwise": "average over N oracles, then worst-case",
        "adaptive_or_nonadaptive": "explicitly states classical measurement control can be coherently replaced",
        "fixed_or_arbitrary_phase": "standard oracle",
        "ancillas": "enlarged Hilbert space allowed",
        "exact_constant": "exact optimal success/query tradeoff",
        "asymptotic_bound": "Theta(sqrt(N))",
        "relation_to_v1_theorem": "stronger exact singleton result; not multiple-subset phase-sensitive formula",
        "relation_to_adaptive_extension": "closest explicit prior statement for deferred measurement",
        "novelty_implication": "singleton adaptive/coherent search result preexists",
    },
    {
        "citation_id": "Hoyer2000",
        "authors": "Peter Hoyer",
        "title": "Arbitrary phases in quantum amplitude amplification",
        "year": 2000,
        "venue": "Physical Review A 62:052304",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1103/PhysRevA.62.052304",
        "arxiv_id": "quant-ph/0006031",
        "primary_url": "https://arxiv.org/html/quant-ph/0006031",
        "theorem_or_result_location": "Theorem 1 and Section V phase condition",
        "model": "amplitude amplification with arbitrary phases",
        "number_of_marked_items": "general initial good probability a",
        "average_worst_or_pointwise": "constructive pointwise amplification",
        "adaptive_or_nonadaptive": "fixed coherent iterations",
        "fixed_or_arbitrary_phase": "arbitrary matched phases",
        "ancillas": "through underlying algorithm A",
        "exact_constant": "exact phase-matching condition",
        "asymptotic_bound": "Theta(1/sqrt(a))",
        "relation_to_v1_theorem": "arbitrary-phase achievability, not v1 lower-bound coefficient",
        "relation_to_adaptive_extension": "does not analyze history-controlled phases",
        "novelty_implication": "arbitrary-phase search itself is known",
    },
    {
        "citation_id": "BHMT2002",
        "authors": "Gilles Brassard; Peter Hoyer; Michele Mosca; Alain Tapp",
        "title": "Quantum Amplitude Amplification and Estimation",
        "year": 2002,
        "venue": "Contemporary Mathematics 305:53-74",
        "publication_status": "peer-reviewed book chapter",
        "doi": "10.1090/conm/305/05215",
        "arxiv_id": "quant-ph/0005055",
        "primary_url": "https://arxiv.org/html/quant-ph/0005055",
        "theorem_or_result_location": "Theorems 2-4 and equation for sin^2((2j+1)theta_a)",
        "model": "amplitude amplification of arbitrary algorithm A",
        "number_of_marked_items": "captured by arbitrary initial good mass a",
        "average_worst_or_pointwise": "pointwise construction",
        "adaptive_or_nonadaptive": "QSearch uses measurement/random iteration counts",
        "fixed_or_arbitrary_phase": "standard amplitude amplification",
        "ancillas": "allowed through A",
        "exact_constant": "exact success formula for construction",
        "asymptotic_bound": "Theta(1/sqrt(a))",
        "relation_to_v1_theorem": "Grover tightness/achievability preexists",
        "relation_to_adaptive_extension": "adaptive expected-time algorithm, not hard-cap upper bound",
        "novelty_implication": "quadratic achievability is known",
    },
    {
        "citation_id": "DohotaruHoyer2009",
        "authors": "Catalin Dohotaru; Peter Hoyer",
        "title": "Exact quantum lower bound for Grover's problem",
        "year": 2009,
        "venue": "Quantum Information and Computation 9(5-6):533-540",
        "publication_status": "peer-reviewed journal",
        "doi": "10.26421/QIC9.5-6-12",
        "arxiv_id": "0810.3647",
        "primary_url": "https://arxiv.org/html/0810.3647",
        "theorem_or_result_location": "Theorems 8 and 9",
        "model": "unique-marked unstructured query search",
        "number_of_marked_items": "one",
        "average_worst_or_pointwise": "uniform success requirement",
        "adaptive_or_nonadaptive": "standard query algorithm",
        "fixed_or_arbitrary_phase": "standard oracle",
        "ancillas": "general algorithm",
        "exact_constant": "exact angle lower bound",
        "asymptotic_bound": "Theta(sqrt(N))",
        "relation_to_v1_theorem": "exact singleton result stronger than coarse v1 specialization",
        "relation_to_adaptive_extension": "supports standard query-model generality",
        "novelty_implication": "exact singleton optimality preexists",
    },
    {
        "citation_id": "AmbainisDeWolf2001",
        "authors": "Andris Ambainis; Ronald de Wolf",
        "title": "Average-case quantum query complexity",
        "year": 2001,
        "venue": "Journal of Physics A 34(35):6741-6754",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1088/0305-4470/34/35/302",
        "arxiv_id": "quant-ph/9904079",
        "primary_url": "https://arxiv.org/html/quant-ph/9904079",
        "theorem_or_result_location": "Sections 2-4 general average-case framework",
        "model": "average-case Boolean query complexity",
        "number_of_marked_items": "not the fixed-M marked-subset theorem",
        "average_worst_or_pointwise": "average input distributions",
        "adaptive_or_nonadaptive": "query algorithms",
        "fixed_or_arbitrary_phase": "Boolean oracle",
        "ancillas": "standard query model",
        "exact_constant": "no v1 coefficient",
        "asymptotic_bound": "problem-dependent average-case relations",
        "relation_to_v1_theorem": "average-case framework preexists; distribution differs",
        "relation_to_adaptive_extension": "does not supply the v2 construction",
        "novelty_implication": "average-case query analysis is known",
    },
    {
        "citation_id": "GilyenArunachalamWiebe2019",
        "authors": "Andras Gilyen; Srinivasan Arunachalam; Nathan Wiebe",
        "title": "Optimizing quantum optimization algorithms via faster quantum gradient computation",
        "year": 2019,
        "venue": "SODA 2019:1425-1444",
        "publication_status": "peer-reviewed proceedings",
        "doi": "10.1137/1.9781611975482.87",
        "arxiv_id": "1711.00465",
        "primary_url": "https://arxiv.org/html/1711.00465",
        "theorem_or_result_location": "Theorem 2, hybrid method for arbitrary phase oracles",
        "model": "controlled arbitrary phase-oracle distinction",
        "number_of_marked_items": "general finite family of functions",
        "average_worst_or_pointwise": "distinguishing every function from reference",
        "adaptive_or_nonadaptive": "general T-query algorithm",
        "fixed_or_arbitrary_phase": "arbitrary continuous phases and inverse",
        "ancillas": "standard general algorithm",
        "exact_constant": "1/3-style distinguishing constant; squared phase differences",
        "asymptotic_bound": "family-dependent hybrid lower bound",
        "relation_to_v1_theorem": "closest arbitrary-phase hybrid source, but not sum-of-slot phase coefficient",
        "relation_to_adaptive_extension": "controlled phase oracles explicitly modeled",
        "novelty_implication": "phase-oracle hybrid methods preexist",
    },
    {
        "citation_id": "BenchasattabuseEtAl2025",
        "authors": "Naphan Benchasattabuse; Andreas Bartschi; Luis Pedro Garcia-Pintos; John Golden; Nathan Lemons; Stephan Eidenbenz",
        "title": "Lower bounds on the number of rounds of QAOA required for guaranteed approximation ratios",
        "year": 2025,
        "venue": "arXiv:2308.15442v4",
        "publication_status": "preprint inspected at v4",
        "doi": "",
        "arxiv_id": "2308.15442",
        "primary_url": "https://arxiv.org/html/2308.15442",
        "theorem_or_result_location": "Corollary 2 and Theorem 5, Section VII",
        "model": "QAOA search phase separator with specified initial/mixer conditions",
        "number_of_marked_items": "m",
        "average_worst_or_pointwise": "guaranteed success lambda",
        "adaptive_or_nonadaptive": "fixed p-round protocol",
        "fixed_or_arbitrary_phase": "adjustable phase separator",
        "ancillas": "not central",
        "exact_constant": "explicit p bounds with 2pi normalization",
        "asymptotic_bound": "Omega(sqrt(N/m)) in search specialization",
        "relation_to_v1_theorem": "QAOA unstructured-search application preexists under different assumptions/bound",
        "relation_to_adaptive_extension": "does not account for trained total queries",
        "novelty_implication": "a broad claim of first QAOA search application is unavailable",
    },
    {
        "citation_id": "AmbainisKokainisVihrovs2023",
        "authors": "Andris Ambainis; Martins Kokainis; Jevgenijs Vihrovs",
        "title": "Improved Algorithm and Lower Bound for Variable Time Quantum Search",
        "year": 2023,
        "venue": "arXiv:2302.06749; TQC 2023",
        "publication_status": "conference/preprint",
        "doi": "10.4230/LIPIcs.TQC.2023.8",
        "arxiv_id": "2302.06749",
        "primary_url": "https://arxiv.org/abs/2302.06749",
        "theorem_or_result_location": "main algorithm and lower-bound results",
        "model": "different checking times across search items",
        "number_of_marked_items": "variable-time search",
        "average_worst_or_pointwise": "worst-case algorithm/lower bound",
        "adaptive_or_nonadaptive": "variable-time framework",
        "fixed_or_arbitrary_phase": "standard search access",
        "ancillas": "general",
        "exact_constant": "no v2 expected-stopping formula",
        "asymptotic_bound": "problem-specific variable-time bound",
        "relation_to_v1_theorem": "different resource model",
        "relation_to_adaptive_extension": "warns that variable time is a distinct formal model",
        "novelty_implication": "does not settle mean stopping-time substitution audited here",
    },
    {
        "citation_id": "BeasleyChristofides1989",
        "authors": "John E. Beasley; Nicos Christofides",
        "title": "An algorithm for the resource constrained shortest path problem",
        "year": 1989,
        "venue": "Networks 19(4):379-394",
        "publication_status": "peer-reviewed journal",
        "doi": "10.1002/net.3230190402",
        "arxiv_id": "",
        "primary_url": "https://onlinelibrary.wiley.com/doi/abs/10.1002/net.3230190402",
        "theorem_or_result_location": "problem definition and integer-programming formulation in abstract/article",
        "model": "explicit graph with costs, resources, and budgets",
        "number_of_marked_items": "not a marked-set oracle model",
        "average_worst_or_pointwise": "explicit-instance optimization",
        "adaptive_or_nonadaptive": "classical exact algorithm",
        "fixed_or_arbitrary_phase": "not applicable",
        "ancillas": "not applicable",
        "exact_constant": "not applicable",
        "asymptotic_bound": "not a quantum query lower bound",
        "relation_to_v1_theorem": "defines the explicit-input target whose side information violates v1 assumptions",
        "relation_to_adaptive_extension": "not applicable",
        "novelty_implication": "RCSP bridge needs a separate reduction",
    },
]


def main() -> None:
    RESULT_ROOT.mkdir(parents=True, exist_ok=True)
    log = pd.DataFrame(
        [
            {
                "search_id": sid,
                "timestamp_utc": TIMESTAMP,
                "query": query,
                "source_database_or_domain": domain,
                "results_screened": screened,
                "sources_opened": opened,
                "sources_included": included,
                "notes": "Primary-source-only screening; no absence result treated as novelty proof.",
            }
            for sid, query, domain, screened, opened, included in SEARCHES
        ]
    )
    atomic_write_csv(RESULT_ROOT / "prior_art_search_log.csv", log)
    atomic_write_csv(RESULT_ROOT / "prior_art_matrix.csv", pd.DataFrame(SOURCES))


if __name__ == "__main__":
    main()
